# Pre-commit hooks configuration for the MongoDB Replica Set project
# This file configures automated code quality checks that run before each commit

repos:
  # Basic pre-commit hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-json
      - id: check-merge-conflict
      - id: debug-statements

  # Password and secret detection
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.4.0
    hooks:
      - id: detect-secrets
        args: ['--baseline', '.secrets.baseline']
        exclude: |
          (?x)^(
              \.secrets\.baseline|
              \.env\.example|
              passwords_and_credentials\.txt|
              docs/.*\.md|
              README\.md
          )$

  # Go linting
  - repo: https://github.com/golangci/golangci-lint
    rev: v1.54.0
    hooks:
      - id: golangci-lint
        args: [--fix]

  # Python formatting and linting
  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black
        language_version: python3

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: [--profile=black]

  - repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        args: [--max-line-length=88, --extend-ignore=E203,W503]

  # Python security scanning
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.5
    hooks:
      - id: bandit
        args: [-r, ., -f, json, -o, bandit-report.json]
        exclude: |
          (?x)^(
              tests/|
              docs/|
              \.venv/|
              venv/
          )$

  # Type checking for Python
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.3.0
    hooks:
      - id: mypy
        additional_dependencies: [types-all]
        exclude: |
          (?x)^(
              tests/|
              docs/|
              \.venv/|
              venv/
          )$

  # JavaScript/Node.js linting
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.44.0
    hooks:
      - id: eslint
        files: \.(js|jsx|ts|tsx)$
        types: [file]
        additional_dependencies:
          - eslint@8.44.0
          - '@eslint/js'
          - 'eslint-config-prettier'
          - 'eslint-plugin-security'

  # Dockerfile linting
  - repo: https://github.com/hadolint/hadolint
    rev: v2.12.0
    hooks:
      - id: hadolint-docker
        args: [--ignore, DL3008, --ignore, DL3009]

  # YAML/JSON validation
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-yaml
      - id: check-json
      - id: yamllint
        args: [--format, parsable, --strict]

  # Markdown linting
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.35.0
    hooks:
      - id: markdownlint
        args: [--fix]

  # Custom password detection hook
  - repo: local
    hooks:
      - id: password-check
        name: Password Detection
        entry: python3 scripts/check_passwords.py
        language: python
        files: \.(py|js|go|yml|yaml|md|txt)$
              exclude: |
        (?x)^(
            \.secrets\.baseline|
            \.env\.example|
            passwords_and_credentials\.txt|
            docs/.*\.md|
            README\.md|
            node_modules/|
            \.git/
        )$ 